/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package compisproyect;

import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.io.PrintWriter;
import java.io.Reader;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;

/**
 *
 * @author herma
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBuscarArchivo = new javax.swing.JButton();
        txtListado = new javax.swing.JScrollPane();
        txtListado1 = new javax.swing.JTextArea();
        btnGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnBuscarArchivo.setLabel("Buscar Archivo");
        btnBuscarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarArchivoActionPerformed(evt);
            }
        });

        txtListado1.setColumns(20);
        txtListado1.setRows(5);
        txtListado.setViewportView(txtListado1);

        btnGuardar.setText("Guardar Archivo");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(txtListado, javax.swing.GroupLayout.DEFAULT_SIZE, 592, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnBuscarArchivo, javax.swing.GroupLayout.DEFAULT_SIZE, 225, Short.MAX_VALUE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBuscarArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtListado, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        btnBuscarArchivo.getAccessibleContext().setAccessibleName("btnBuscarArchivo");

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public String resultadoFinal = "";
    private void btnBuscarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarArchivoActionPerformed
        // TODO add your handling code here:
                                             
        JFileChooser file = new JFileChooser();
        file.showOpenDialog(this);
        try {
            
            Reader lector = new BufferedReader(new FileReader(file.getSelectedFile()));
            Lexer lexer = new Lexer(lector);
            String resultado = "";
            List<String> list = new ArrayList<String>();
            while(true)
            {
                Tokens tokens = lexer.yylex();
  
                if (tokens == null) 
                {
                    return;
                }
                switch(tokens)
                {
                    case ERROR:
                        resultado += "Simbolo no definido";        
                    break;
                    case Enteros:
                        resultado += "<" + lexer.lexeme + ", Es Un:" + tokens + ">";
                        list.add("Enteros");
                        break;
                        
                    case Simbolo:
                        resultado += "<" + lexer.lexeme + ", Es Un:" + tokens + ">";
                        list.add(lexer.lexeme);
                        if(lexer.lexeme.compareTo(";")==0)
                        {
                            Sintaxis sintaxis = new Sintaxis(list);
                            list.clear();
                        }
                       
                        break;
                    
                    case Reservadas:case Float:case String1:case Separador:case Operador:case Comparador:
                    case ComentarioMultilinea:
                    case ComentarioLinea: 
                        resultado += "<" + lexer.lexeme + ", Es Un:" + tokens + ">";
                        list.add(lexer.lexeme);
                        break;
                    
                    
                    case ErrorIdentificador: 
                    case ErrorString:
                    case ErrorMultilinea:
                       resultado += "<" + lexer.lexeme + ", Error en la fila:" + (lexer.linea + 1)  + " Columna: " + (lexer.columna + 1); 
                        
                        break;
                    
                    
                    case Identificador:
                        list.add("Identificador");
                        if (lexer.lexeme.length()<=31) {
                            resultado += "<" + lexer.lexeme + ", Es Un:" + tokens + ">";
                        }
                        else
                        {
                            String cadena = lexer.lexeme;
                            cadena = cadena.substring(0,30);
                            resultado += "<" + cadena + ", Es Un:" + tokens + ">";
                        }
                        break;
                    default:
                        resultado+= "Token: " + tokens;
                
                }
                resultado += "\n";
                txtListado1.setText(resultado);
                resultadoFinal = resultado;
            }
        }
        catch (IOException ex) 
        {
             
        }
    }//GEN-LAST:event_btnBuscarArchivoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        // TODO add your handling code here:
        JFileChooser guardarComo = new JFileChooser();
        guardarComo.setApproveButtonText("Guardar");
        guardarComo.showSaveDialog(null);
        File archivo  = new File(guardarComo.getSelectedFile()+".out");
        try
        {
            BufferedWriter salida = new BufferedWriter(new FileWriter(archivo)); 
            salida.write(resultadoFinal);
            salida.close();
        }
        catch(Exception ex)
        {
            
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarArchivo;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JScrollPane txtListado;
    private javax.swing.JTextArea txtListado1;
    // End of variables declaration//GEN-END:variables
}
