/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package compisproyect;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.PrintWriter;
import javax.swing.JFileChooser;

/**
 *
 * @author herma
 */
public class Ventana extends javax.swing.JFrame {

    /**
     * Creates new form Ventana
     */
    public Ventana() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnBuscarArchivo = new javax.swing.JButton();
        txtListado = new javax.swing.JScrollPane();
        txtListado1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnBuscarArchivo.setLabel("Buscar Archivo");
        btnBuscarArchivo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarArchivoActionPerformed(evt);
            }
        });

        txtListado1.setColumns(20);
        txtListado1.setRows(5);
        txtListado.setViewportView(txtListado1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(txtListado, javax.swing.GroupLayout.DEFAULT_SIZE, 368, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnBuscarArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(42, 42, 42))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtListado, javax.swing.GroupLayout.PREFERRED_SIZE, 321, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscarArchivo, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        btnBuscarArchivo.getAccessibleContext().setAccessibleName("btnBuscarArchivo");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBuscarArchivoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarArchivoActionPerformed
        // TODO add your handling code here:
        try {
            
            JFileChooser file = new JFileChooser();
            file.showOpenDialog(this);
            File abrir = file.getSelectedFile();
            
            if (abrir!=null)
            {
                FileReader leerArchivo = new FileReader(abrir);
                BufferedReader leyendo = new BufferedReader(leerArchivo);
                String linea = leyendo.readLine();
                String resultado = "";
                while(linea!=null)
                {
                    File file2 = new File("C:/Users/herma/Desktop/Archivos Pueba Compis/archivo.txt");
                    PrintWriter escribir = new PrintWriter(file2);
                    escribir.print(linea);
                    escribir.close();
                    FileReader lectura = new FileReader("C:/Users/herma/Desktop/Archivos Pueba Compis/archivo.txt");
                    BufferedReader lee = new BufferedReader(lectura);
                
                    Lexer lexer = new Lexer(lee);
                
                    boolean salir = false;
                    while(!salir)
                    {
                        Tokens tokens = lexer.yylex();
                        
                        if (tokens==null) 
                        {
                            resultado +="FIN";
                            txtListado1.setText(resultado);
                            salir = true;
                        }
                        else
                        {
                           switch(tokens)
                            {
                                case ERROR:
                                resultado += "Simbolo no definido";
                            
                                break;
                                case  Reservadas: case Numero: case Identificador:
                                resultado += "<" + lexer.lexeme + ", Es Un:" + tokens + ">";
                            
                                break;
                            
                                default: 
                                resultado+= "Token: " + tokens + "\n";
                            
                            } 
                        }
                        
                        resultado += "\n";
                    }
                    lectura.close();
                    lee.close();
                    linea = leyendo.readLine();
                }
                
               
            }
        }
        catch (Exception e) 
        {
            
        }
    }//GEN-LAST:event_btnBuscarArchivoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscarArchivo;
    private javax.swing.JScrollPane txtListado;
    private javax.swing.JTextArea txtListado1;
    // End of variables declaration//GEN-END:variables
}
